# Generated by Django 2.1.5 on 2020-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherStu', '0025_auto_20200727_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq_question',
            name='que_Image',
            field=models.ImageField(default='images/Blank', max_length=1000, upload_to='images/'),
        ),
    ]
